// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ8YNPJIc_T-NWFqL0y7M5-P8mzyagty4',
    appId: '1:646756438260:web:0bf859e9e1deb050744ea1',
    messagingSenderId: '646756438260',
    projectId: 'inventory-management-sys-c1273',
    authDomain: 'inventory-management-sys-c1273.firebaseapp.com',
    storageBucket: 'inventory-management-sys-c1273.appspot.com',
    measurementId: 'G-EFVWS4852L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1i5DpIP4-YVzDL3xdBJwdM2hDfnEjymU',
    appId: '1:646756438260:android:d625f118ed229f8d744ea1',
    messagingSenderId: '646756438260',
    projectId: 'inventory-management-sys-c1273',
    storageBucket: 'inventory-management-sys-c1273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBUjpF4gXgwmw0Qr3uTISBBr0k7S0og0I',
    appId: '1:646756438260:ios:caac71bc3250d580744ea1',
    messagingSenderId: '646756438260',
    projectId: 'inventory-management-sys-c1273',
    storageBucket: 'inventory-management-sys-c1273.appspot.com',
    iosClientId: '646756438260-82ksnsvi9mggfme972e1m2hnfged16jp.apps.googleusercontent.com',
    iosBundleId: 'com.ims.app',
  );
}
